# Generated by Django 5.1.6 on 2025-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the footwear', max_length=100)),
                ('brand', models.CharField(help_text='Brand of the footwear', max_length=50)),
                ('category', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Formal', 'Formal'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Sports', 'Sports'), ('Casual', 'Casual'), ('Heels', 'Heels'), ('Slippers', 'Slippers')], help_text='Type of footwear', max_length=20)),
                ('size', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Size of the footwear', max_length=5)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Yellow', 'Yellow')], help_text='Color of the footwear', max_length=20)),
                ('material', models.CharField(help_text='Material used (e.g., Leather, Canvas, Synthetic)', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Available stock')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the footwear')),
                ('image', models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='footwear_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Date when footwear was added')),
            ],
        ),
    ]
