# Generated by Django 5.1.6 on 2025-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('jewelry', 'Jewelry'), ('bags', 'Bags'), ('hats', 'Hats'), ('belts', 'Belts'), ('sunglasses', 'Sunglasses'), ('watches', 'Watches')], max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='accessories/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
