# Generated by Django 5.1.6 on 2025-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('TS', 'T-Shirt'), ('SH', 'Shirt'), ('JK', 'Jacket'), ('PN', 'Pants'), ('SW', 'Sweater'), ('DR', 'Dress')], max_length=2)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='clothing_images/')),
            ],
        ),
    ]
