# Generated by Django 5.1.6 on 2025-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0002_alter_clothing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Jacket', 'Jacket'), ('Pants', 'Pants'), ('Sweater', 'Sweater'), ('Dress', 'Dress'), ('Hoodies', 'Hoodies'), ('Trousers', 'Trousers')], max_length=20),
        ),
    ]
